services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: adrien_owner
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: adrien
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
