name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "./docker-compose.yml"
          services: |
            db
          up-flags: "--build --detach"
          down-flags: "--volumes --remove-orphans"
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL: postgresql://adrien_owner:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/adrien

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://adrien_owner:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/adrien
        run: npx prisma migrate deploy

      - name: Build the project
        run: npm run build

      - name: Tear down Docker Compose
        if: always()
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "./docker-compose.yml"
          services: |
            db
          down-flags: "--volumes --remove-orphans"
